# 开发环境配置

# 覆盖默认配置
# 秘书系统配置
io:
  secretarymcp:
    storage:
      base-dir: ${user.home}/secretary-data
    mcp:
      client:
        url: http://localhost:8081/mcp
        connectionTimeout: 30
      server:
        port: 8082

# 增强开发环境的日志输出
logging:
  level:
    "[io.secretarymcp]": DEBUG
    "[org.springframework.web]": DEBUG
    "[reactor.netty.http]": DEBUG