# 基础配置 - 适用于所有模式
io:
  secretarymcp:
    storage:
      base-dir: ${user.home}/secretary-data

# 兼容配置
secretary:
  storage:
    base-dir: ${io.secretarymcp.storage.base-dir}

# 服务器基本配置
server:
  port: 8765

# 日志配置
logging:
  file:
    name: logs/secretary-mcp.log
    max-size: 10MB
    max-history: 10
  pattern:
    console: ""
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    io.secretarymcp: INFO

# Spring基本配置 - 明确使用reactive
spring:
  profiles:
    active: sse
  threads:
    virtual:
      enabled: true
  main:
    banner-mode: off
    web-application-type: reactive  # 明确设置为reactive
  web:
    resources:
      static-locations: classpath:/static/
  devtools:
    restart:
      enabled: false  # 禁用DevTools热重启功能

# 调整Netty相关配置
reactor:
  netty:
    ioWorkerCount: 8

# MCP配置 - 默认使用SSE模式
mcp:
  transport: sse
  sse:
    endpoint: /sse

# ----------------------------------------
# STDIO模式配置 (仅在使用--stdio参数时激活)
# ----------------------------------------
---
spring:
  config:
    activate:
      on-profile: stdio
  main:
    web-application-type: none  # STDIO模式不需要web服务器

# MCP配置 - STDIO模式
mcp:
  transport: stdio